# Generated by Django 3.2.8 on 2021-10-05 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('url', models.CharField(db_column='url', default='No URL', max_length=20)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, default=0, max_digits=1000)),
                ('description', models.TextField(db_column='description', default='Empty')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ids', models.TextField(db_column='item_ids', default='')),
                ('user_name', models.TextField(db_column='user_name', default='')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wish_lists',
            },
        ),
    ]
